Repository wliamp/spring-boot-starter-bundle, pull requests merged in 2025-08, with the labels that each got.

#5 dev/token
  starter-token/build.gradle
  starter-token/src/main/kotlin/io/wliamp/token/config/TokenAutoConfig.kt
  starter-token/src/main/kotlin/io/wliamp/token/util/ExternalToken.kt
  starter-token/src/main/kotlin/io/wliamp/token/util/InternalToken.kt
  starter-token/src/main/kotlin/io/wliamp/token/util/InternalTokenWrapper.kt
Labels: duplicate

#7 bug(token): fix beans missing
  starter-token/build.gradle
  starter-token/settings.gradle
  starter-token/src/main/kotlin/io/wliamp/token/config/TokenAutoConfig.kt
  starter-token/src/main/kotlin/io/wliamp/token/data/FacebookParty.kt
  starter-token/src/main/kotlin/io/wliamp/token/data/GoogleParty.kt
  starter-token/src/main/kotlin/io/wliamp/token/data/ZaloParty.kt
  starter-token/src/main/kotlin/io/wliamp/token/util/ExternalToken.kt
  starter-token/src/test/kotlin/io/wliamp/token/TestInternalToken.kt
  starter-token/src/test/kotlin/io/wliamp/token/TestJwtDecoder.kt
  starter-token/src/test/kotlin/io/wliamp/token/TestJwtEncoder.kt
Labels: bug

#9 refactor(provider): migrate code form module starter-token for Oauth verify function
  build.gradle
  starter-provider/build.gradle
  starter-provider/src/main/kotlin/io/github/wliamp/provider/config/AutoConfiguration.kt
  starter-provider/src/main/kotlin/io/github/wliamp/provider/config/ProviderAutoConfig.kt
  starter-provider/src/main/kotlin/io/github/wliamp/provider/config/ProviderProperties.kt
  starter-provider/src/main/kotlin/io/github/wliamp/provider/data/FacebookOauth.kt
  starter-provider/src/main/kotlin/io/github/wliamp/provider/data/GoogleOauth.kt
  starter-provider/src/main/kotlin/io/github/wliamp/provider/data/Oauth.kt
  starter-provider/src/main/kotlin/io/github/wliamp/provider/data/ZaloOauth.kt
  starter-provider/src/main/kotlin/io/github/wliamp/provider/util/OauthVerifier.kt
  starter-provider/src/main/resources/META-INF/spring/org.springframework.boot.autoconfigure.autoconfiguration.imports
Labels: duplicate

#15 module provider-payment
  build.gradle
  provider-payment/src/main/kotlin/io/github/wliamp/pro/pay/config/PaymentProviderAutoConfig.kt
  provider-payment/src/main/kotlin/io/github/wliamp/pro/pay/config/PaymentProviderProps.kt
  provider-payment/src/main/kotlin/io/github/wliamp/pro/pay/data/AuthorizeNetGtw.kt
  provider-payment/src/main/kotlin/io/github/wliamp/pro/pay/data/VnPayGtw.kt
  provider-payment/src/main/kotlin/io/github/wliamp/pro/pay/util/PaymentProvider.kt
Labels: enhancement

#17 module provider-verify
  provider-verify/src/main/kotlin/io/github/wliamp/pro/vrf/config/VerifyProviderAutoConfig.kt
  provider-verify/src/main/kotlin/io/github/wliamp/pro/vrf/config/VerifyProviderProperties.kt
  provider-verify/src/main/kotlin/io/github/wliamp/pro/vrf/data/FacebookOauth.kt
  provider-verify/src/main/kotlin/io/github/wliamp/pro/vrf/data/GoogleOauth.kt
  provider-verify/src/main/kotlin/io/github/wliamp/pro/vrf/data/IOauth.kt
  provider-verify/src/main/kotlin/io/github/wliamp/pro/vrf/data/ZaloOauth.kt
  provider-verify/src/main/kotlin/io/github/wliamp/pro/vrf/util/OauthProvider.kt
  provider-verify/src/main/kotlin/io/github/wliamp/provider/config/ProviderAutoConfig.kt
  provider-verify/src/main/kotlin/io/github/wliamp/provider/config/ProviderProperties.kt
  provider-verify/src/main/kotlin/io/github/wliamp/provider/data/FacebookOauth.kt
  provider-verify/src/main/kotlin/io/github/wliamp/provider/data/GoogleOauth.kt
  provider-verify/src/main/kotlin/io/github/wliamp/provider/data/ZaloOauth.kt
  provider-verify/src/main/kotlin/io/github/wliamp/provider/util/OauthVerifier.kt
  provider-verify/src/main/resources/META-INF/spring/org.springframework.boot.autoconfigure.autoconfiguration.imports
  provider-verify/src/test/kotlin/io/github/wliamp/pro/vrf/TestClass.kt
Labels: bug, duplicate

#23 module provider-payment
  provider-payment/src/main/kotlin/io/github/wliamp/pro/pay/AuthorizeNetRequest.kt
  provider-payment/src/main/kotlin/io/github/wliamp/pro/pay/PaymentProvider.kt
  provider-payment/src/main/kotlin/io/github/wliamp/pro/pay/VnPayRequest.kt
  provider-payment/src/main/kotlin/io/github/wliamp/pro/pay/ZaloPayRequest.kt
  provider-payment/src/main/kotlin/io/github/wliamp/pro/pay/config/PaymentProviderAutoConfig.kt
  provider-payment/src/main/kotlin/io/github/wliamp/pro/pay/config/PaymentProviderProps.kt
  provider-payment/src/main/kotlin/io/github/wliamp/pro/pay/cus/AuthorizeNetCus.kt
  provider-payment/src/main/kotlin/io/github/wliamp/pro/pay/cus/OCus.kt
  provider-payment/src/main/kotlin/io/github/wliamp/pro/pay/cus/VnPayCus.kt
  provider-payment/src/main/kotlin/io/github/wliamp/pro/pay/cus/ZaloPayCus.kt
  provider-payment/src/main/kotlin/io/github/wliamp/pro/pay/gtw/IGtw.kt
  provider-payment/src/main/kotlin/io/github/wliamp/pro/pay/gtw/ORequest.kt
  provider-payment/src/main/kotlin/io/github/wliamp/pro/pay/gtw/VnPayGtw.kt
  provider-payment/src/main/kotlin/io/github/wliamp/pro/pay/gtw/ZaloPayGtw.kt
  provider-payment/src/main/kotlin/io/github/wliamp/pro/pay/impl/AuthorizeNetGtw.kt
  provider-payment/src/main/kotlin/io/github/wliamp/pro/pay/impl/IGtw.kt
  provider-payment/src/main/kotlin/io/github/wliamp/pro/pay/impl/VnPayGtw.kt
  provider-payment/src/main/kotlin/io/github/wliamp/pro/pay/impl/ZaloPayGtw.kt
  provider-payment/src/main/kotlin/io/github/wliamp/pro/pay/sys/AuthorizeNetSys.kt
  provider-payment/src/main/kotlin/io/github/wliamp/pro/pay/sys/OSys.kt
  provider-payment/src/main/kotlin/io/github/wliamp/pro/pay/sys/VnPaySys.kt
  provider-payment/src/main/kotlin/io/github/wliamp/pro/pay/sys/ZaloPaySys.kt
  provider-payment/src/main/kotlin/io/github/wliamp/pro/pay/util/Utilities.kt
Labels: duplicate, enhancement
